version: '3.8'

services:
  grafana:
    image: grafana/grafana:9
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  app:
    build: .
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
    depends_on:
      - grafana

volumes:
  grafana-data:
